apiVersion: v1
kind: ConfigMap
metadata:
  name: streaming-config
data:
  # property-like keys; each key maps to a simple value
  kafka_sensor_topic_name: "mytopic"
  kafka_frontend_topic_name: "frontup"